spring:
  application:
    name: lotto-pattern-generator

  profiles:
    default: local

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  lotto:
    seed-csv: data/winning-numbers.csv
    auto-update:
      enabled: true
